---
AWSTemplateFormatVersion: '2010-09-09'
Description: A cloudformation template to create a calculation service lambda functions and SNS topic
Parameters:
  pSnsTopicName:
    Type: String
  pOtherAccountID:
    Type: String
  pLambdaCodeBucket:
    Type: String
  pCalServiceCodeS3KeyPath:
    Type: String
Resources:
  CalculationSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref pSnsTopicName
  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CalculationSNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowSubscriptionFromOtherAccount
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${pOtherAccountID}:root"
            Action: 
            - SNS:Subscribe
            - SNS:Publish
            Resource: !Ref CalculationSNSTopic
  lfnLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: lambdaCloudWatchPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"
      - PolicyName: snsPublish
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - SNS:Publish
            Resource:
              Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${pSnsTopicName}
  lfnCalcService:
    Type: AWS::Lambda::Function
    DependsOn:
    - lfnLambdaRole
    Properties:
      Environment:
        Variables:
          SNS_TOPIC_ARN:
            Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${pSnsTopicName}
      Architectures:
      - x86_64
      Runtime: go1.x
      Handler: main
      Timeout: '120'
      Code:
        S3Bucket:
          Ref: pLambdaCodeBucket
        S3Key:
          Ref: pCalServiceCodeS3KeyPath
      Description: This is calculation service lambda function
      FunctionName: calculation-service-lambda
      Role:
        Fn::GetAtt:
        - lfnLambdaRole
        - Arn
  snsPermInvokeCalcService:
    Type: AWS::Lambda::Permission
    DependsOn:
    - lfnCalcService
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - lfnCalcService
        - Arn
      Principal: sns.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${pSnsTopicName}
  snsSubscriptionCalcService:
    Type: AWS::SNS::Subscription
    DependsOn:
    - lfnCalcService
    Properties:
      Endpoint:
        Fn::GetAtt:
        - lfnCalcService
        - Arn
      FilterPolicy:
        name:
        - SumRequested
      Protocol: lambda
      TopicArn:
        Fn::Sub: arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${pSnsTopicName}
Outputs:
  SNSTopicARN:
    Description: SNS Topic ARN
    Value: !Ref CalculationSNSTopic